### ISSUE TITLE
I followed the instruction from #1116 and #1129, but can't make kcptun plugin run.

### ISSUE THREAD

**Issue by dmxixi** [shadowsocks/shadowsocks-android#1191]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.1 Build NUF26N*
* Device:  Google Nexus6P*
* Shadowsocks version:  server version v3.0.0, android version v4.1.3 

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:RC4-MD5
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
I follow the description from #1116 and #1129 , but still can't make KCPTUN plugin run.

My shadowsocks settings:
Server: server IP address;
Remote Port: server SS port (also tried server kcptun port);
Local Port: 1080;
Password: SS password;
Encrypt Method: ss server encrypt mode

plugin version: 3.8
kcptun plugin setting:
key=kcpPassword; remoteaddr=serverIP:kcpPort; autoexpire=60; crypt=aes-192; mode=fast2

I also tried to set Remote Port to kcp port, but it still didn't work. What should I do?

**Comment by fiercebead** [comment]
Remove spaces after `;`

**Comment by dmxixi** [comment]
Thanks! The problem is solved!

**Comment by jyanchen** [comment]
@dmxixi May I ask you how to fixed this? I still have this problem... thx!

**Comment by dmxixi** [comment]
@jyanchen put a `;` after the each commands, but no "space" after `;`
