### ISSUE TITLE
The popup menu background color following the system theme, but the font color will not change

### ISSUE THREAD

**Issue by onlymash** [shadowsocks/shadowsocks-android#1718]
### Environment

* Android version: 8.1(LineageOS 15.1)
* Shadowsocks version: 4.5.3

### What did you see instead?
If the system enable Dark theme (night mode), the popupmenu background color will be the same as the system.
![screenshot_shadowsocks_20180401-035524](https://user-images.githubusercontent.com/5838634/38167521-c7b763a4-3568-11e8-825c-3b9bfd84e28a.png)

**Comment by Mygod** [comment]
Even though I could not reproduce this issue on any of my devices (seems like most custom ROMs these days don't really want to care about day night features) but I fixed it anyhow. Please wait for fix to be merged by upstream.

**Comment by onlymash** [comment]
@Mygod the bug still exist.
P.S. 夜间模式并不只是自定义 ROM 才有，AOSP 就已经支持，Pixel 手机可以通过使用暗色壁纸开启夜间模式
https://source.android.com/devices/tech/display/night-light
![screenshot_settings_20180410-234029](https://user-images.githubusercontent.com/5838634/38567537-0ee79e12-3d19-11e8-8418-deb5959ade4f.png)

**Comment by iKirby** [comment]
@onlymash AOSP 只有通知栏和快捷设置面板、启动器抽屉会变成暗色，其他地方不变。全局暗色主题还是第三方才有的功能。

**Comment by Mygod** [comment]
Upstream hasn't merged the fix. Please blame @gericop.

**Comment by onlymash** [comment]
@iKirby 只要系统变成暗色主题模式，用系统的颜色值作为背景，肯定是黑色的，然而这里字体写死为黑色，背景又是黑色，就造成这样的后果

**Comment by onlymash** [comment]
@iKirby 其他地方不变是因为每个系统app都是单独写的，这些app并没有适配夜间主题(使用DayNight主题)

**Comment by Mygod** [comment]
Also DayNight theme is different from night light. I haven't seen AOSP has
DayNight feature.

**Comment by Mygod** [comment]
Day night was originally introduced in a developer preview and was removed
in the official release. In fact people has been begging Google to add back
dark mode for years and yet that has not happened.

**Comment by onlymash** [comment]
LineageOS 正在给越来越多系统自带 App 适配夜间主题，普遍采用 DayNight 主题。
https://review.lineageos.org/#/c/LineageOS/android_packages_apps_Updater/+/212457/

**Comment by Mygod** [comment]
Pull requests are welcome.

**Comment by onlymash** [comment]
谷歌目前没有让把代码合并到AOSP，但是他们自己的 Pixel、 Android One 设备都是支持的。可能是考虑到很多应用写的不规范，会出现类似这样的bug，才没有强制让OEM支持

**Comment by Mygod** [comment]
Feel free to go rant on this issue: https://issuetracker.google.com/issues/69759140
