### ISSUE TITLE
DNS spoofed by 0.0.0.0

### ISSUE THREAD

**Issue by IrineSistiana** [shadowsocks/shadowsocks-android#2411]
It seems `0.0.0.0` is part of spoofed IP addresses now. (update: `127.0.0.1` as well)

```
> nslookup www.google.com 223.5.5.5
Server:  public1.alidns.com
Address:  223.5.5.5

Name:    www.google.com
Addresses:  2001::4b7e:7ca2
          0.0.0.0
```

But shadowsocks-android build-in DNS resolver can't filter it away. 

Because we have:

https://github.com/shadowsocks/shadowsocks-android/blob/11a0ecd95e162c70c318cd09e0e5bd545b43ea1e/core/src/main/assets/acl/bypass-lan-china.acl#L3-L4

https://github.com/shadowsocks/shadowsocks-android/blob/11a0ecd95e162c70c318cd09e0e5bd545b43ea1e/core/src/main/java/com/github/shadowsocks/net/LocalDnsServer.kt#L133

Affected route mode: 
Bypass LAN, 
Bypass LAN & mainland China
GFW List

Got err, for example, when testing server latency: `Fail to detect internet connection: Fail to connect to www.google.com/0.0.0.0:443`

Tested on shadowsocks-android version: 5.0.1

**Comment by Mygod** [comment]
Why would you use alidns for remote dns?

**Comment by Mygod** [comment]
Okay on closer inspection, maybe the domain should be handled by proxy_list instead (though I were not able to reproduce this).

@madeye Thoughts?

**Comment by madeye** [comment]
I think we can just remove 0.0.0.0/8 from the bypass list, which didn't make sense here.

**Comment by madeye** [comment]
I cannot reproduce this either.

Actually, all domains in GFWList should be handled with remote DNS. Only if the user is using a Chinese DNS server as remote DNS.

**Comment by madeye** [comment]
@IrineSistiana You may debug around shouldBypass, to see if "www.google.com" got matched in ACL.

**Comment by Mygod** [comment]
Correct. Hostname matcher overrides IP rules.

**Comment by madeye** [comment]
It looks that our current RE2 matcher cannot match anything... @Mygod

**Comment by madeye** [comment]
Looks related to `FullMatch` in RE2.

According to https://regex-golang.appspot.com/assets/html/index.html

`[?:^*|\.]google\.com$` can only partially match `www.google.com`

**Comment by Mygod** [comment]
Oh right lulz.

**Comment by madeye** [comment]
I tried this one `^(|.+\.)google\.com$`, which works well.

**Comment by Mygod** [comment]
It should be fixed now. Either way `google.com` was not handled by our old DNS resolver either so I consider that I did not introduce a new bug. 😛

**Comment by philos3** [comment]
please check it ，the problem is still exist ，when i use 5.0.6
