### ISSUE TITLE
v5.1.1 issues

### ISSUE THREAD

**Issue by qwerttvv** [shadowsocks/shadowsocks-android#2535]
![558418921](https://user-images.githubusercontent.com/56712217/82520061-c8b43480-9b55-11ea-9bce-2f715e8d10bf.jpg)

same config with
https://github.com/shadowsocks/shadowsocks-android/issues/2515

**Comment by madeye** [comment]
@Mygod What do you think? This plugin seems not protect its DNS query with `protect()`?

**Comment by Mygod** [comment]
If that is the case then proxy only mode should work?

**Comment by qwerttvv** [comment]
> 如果是这种情况，那么仅代理模式应该可以工作吗？

yes
it works

**Comment by madeye** [comment]
One workaround is using IP address instead of domain name for your server host name.

**Comment by Mygod** [comment]
Wait what? I think shadowsocks-android currently handles those DNS queries in JVM?

https://github.com/shadowsocks/shadowsocks-android/blob/9711da1c80a5eb3262a418439d52ba14a19d4d45/core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt#L85-L92

**Comment by ExpITSolutions** [comment]
> One workaround is using IP address instead of domain name for your server host name.

I have same issue and IP also don't work.

**Comment by loyess** [comment]
@ExpITSolutions  This plugin is supported in version 5.0.6

**Comment by ExpITSolutions** [comment]
@loyess I think there was a lot of changes in dependences since 5.0.6 and I can't build 5.0.6 from sources, can you show how to build it?

**Comment by loyess** [comment]
@ExpITSolutions  Download directly from Releases

**Comment by qwerttvv** [comment]
> @loyess I think there was a lot of changes in dependences since 5.0.6 and I can't build 5.0.6 from sources, can you show how to build it?

https://github.com/shadowsocks/shadowsocks-android/releases/tag/v5.0.6

here

**Comment by ExpITSolutions** [comment]
@loyess @qwerttvv  yes, I tried, but I need build from source and when I start building there a lot of errors.

**Comment by loyess** [comment]
Still can't solve the problem that cloak plugin can't be used ？

**Comment by madeye** [comment]
Try Cloak 2.2.0 here https://github.com/cbeuw/Cloak-android/releases/tag/v2.2.0, which should fix the problem.

**Comment by loyess** [comment]
@madeye  Installing Cloak 2.2.0 does not solve the problem.

The log is as follows：
```
06-03 20:31:01.025  6939  7302 E libsslocal: 2020-06-03T20:31:01.023+08:00 INFO  shadowsocks 1.8.12
06-03 20:31:01.046  6939  7302 E libsslocal: 2020-06-03T20:31:01.045+08:00 INFO  started plugin "/data/app/com.github.shadowsocks.plugin.ck_client-RrDoO0hGHK4zycsZImCBbA==/lib/arm64/libck-client.so" on 127.0.0.1:42607 <-> <My_Server-IP>:443 (7317)
06-03 20:31:01.501  6939  7302 E libsslocal: panic: runtime error: index out of range [1] with length 1
06-03 20:31:01.503  6939  7302 E libsslocal: goroutine 1 [running]:
06-03 20:31:01.503  6939  7302 E libsslocal: github.com/cbeuw/Cloak/internal/client.ssvToJson(0x400000a112, 0xdf, 0x6070c89e33, 0x1, 0xd)
06-03 20:31:01.503  6939  7302 E libsslocal: 	C:/Users/cbeuw/StudioProjects/Cloak-android/app/src/.deps/Cloak/internal/client/state.go:89 +0x4e0
06-03 20:31:01.503  6939  7302 E libsslocal: github.com/cbeuw/Cloak/internal/client.ParseConfig(0x400000a112, 0xdf, 0x4, 0x0, 0x0)
06-03 20:31:01.503  6939  7302 E libsslocal: 	C:/Users/cbeuw/StudioProjects/Cloak-android/app/src/.deps/Cloak/internal/client/state.go:107 +0x78
06-03 20:31:01.503  6939  7302 E libsslocal: main.main()
06-03 20:31:01.503  6939  7302 E libsslocal: 	C:/Users/cbeuw/StudioProjects/Cloak-android/app/src/.deps/Cloak/cmd/ck-client/ck-client.go:81 +0x71c
06-03 20:31:11.048  6939  7302 E libsslocal: 2020-06-03T20:31:11.047+08:00 WARN  plugin "/data/app/com.github.shadowsocks.plugin.ck_client-RrDoO0hGHK4zycsZImCBbA==/lib/arm64/libck-client.so" for <My_Server-IP>:443 listening on 127.0.0.1:42607 isn't started yet, elapsed 10.0s
06-03 20:31:11.050  6939  7302 E libsslocal: 2020-06-03T20:31:11.050+08:00 ERROR terminating plugin process 7317, error: No such process (os error 3)
06-03 20:31:11.051  6939  7302 E libsslocal: 2020-06-03T20:31:11.050+08:00 ERROR waitpid(7317) error: No child processes (os error 10)
06-03 20:31:11.056  6939  7302 E libsslocal: 2020-06-03T20:31:11.051+08:00 ERROR one of servers exited unexpectly, result: Err(Custom { kind: Other, error: "plugin exited unexpectedly with exit code: 2" })
06-03 20:31:11.056  6939  7302 E libsslocal: thread 'main' panicked at 'aborted with server exited unexpectly', src/bin/local.rs:310:45
06-03 20:31:11.056  6939  7302 E libsslocal: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by madeye** [comment]
> @madeye  Installing Cloak 2.2.0 does not solve the problem.
> 
> The log is as follows：
> ```
> 06-03 20:31:01.025  6939  7302 E libsslocal: 2020-06-03T20:31:01.023+08:00 INFO  shadowsocks 1.8.12
> 06-03 20:31:01.046  6939  7302 E libsslocal: 2020-06-03T20:31:01.045+08:00 INFO  started plugin "/data/app/com.github.shadowsocks.plugin.ck_client-RrDoO0hGHK4zycsZImCBbA==/lib/arm64/libck-client.so" on 127.0.0.1:42607 <-> <My_Server-IP>:443 (7317)
> 06-03 20:31:01.501  6939  7302 E libsslocal: panic: runtime error: index out of range [1] with length 1
> 06-03 20:31:01.503  6939  7302 E libsslocal: goroutine 1 [running]:
> 06-03 20:31:01.503  6939  7302 E libsslocal: github.com/cbeuw/Cloak/internal/client.ssvToJson(0x400000a112, 0xdf, 0x6070c89e33, 0x1, 0xd)
> 06-03 20:31:01.503  6939  7302 E libsslocal: 	C:/Users/cbeuw/StudioProjects/Cloak-android/app/src/.deps/Cloak/internal/client/state.go:89 +0x4e0
> 06-03 20:31:01.503  6939  7302 E libsslocal: github.com/cbeuw/Cloak/internal/client.ParseConfig(0x400000a112, 0xdf, 0x4, 0x0, 0x0)
> 06-03 20:31:01.503  6939  7302 E libsslocal: 	C:/Users/cbeuw/StudioProjects/Cloak-android/app/src/.deps/Cloak/internal/client/state.go:107 +0x78
> 06-03 20:31:01.503  6939  7302 E libsslocal: main.main()
> 06-03 20:31:01.503  6939  7302 E libsslocal: 	C:/Users/cbeuw/StudioProjects/Cloak-android/app/src/.deps/Cloak/cmd/ck-client/ck-client.go:81 +0x71c
> 06-03 20:31:11.048  6939  7302 E libsslocal: 2020-06-03T20:31:11.047+08:00 WARN  plugin "/data/app/com.github.shadowsocks.plugin.ck_client-RrDoO0hGHK4zycsZImCBbA==/lib/arm64/libck-client.so" for <My_Server-IP>:443 listening on 127.0.0.1:42607 isn't started yet, elapsed 10.0s
> 06-03 20:31:11.050  6939  7302 E libsslocal: 2020-06-03T20:31:11.050+08:00 ERROR terminating plugin process 7317, error: No such process (os error 3)
> 06-03 20:31:11.051  6939  7302 E libsslocal: 2020-06-03T20:31:11.050+08:00 ERROR waitpid(7317) error: No child processes (os error 10)
> 06-03 20:31:11.056  6939  7302 E libsslocal: 2020-06-03T20:31:11.051+08:00 ERROR one of servers exited unexpectly, result: Err(Custom { kind: Other, error: "plugin exited unexpectedly with exit code: 2" })
> 06-03 20:31:11.056  6939  7302 E libsslocal: thread 'main' panicked at 'aborted with server exited unexpectly', src/bin/local.rs:310:45
> 06-03 20:31:11.056  6939  7302 E libsslocal: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> ```

Report it to the plug-in maintainer, it crashed when parsing your config.

**Comment by loyess** [comment]
@madeye  Confusingly, the same configuration, the network connection is normal in Android-SS 5.0.6 version.

**Comment by qwerttvv** [comment]
> @madeye Confusingly, the same configuration, the network connection is normal in Android-SS 5.0.6 version.

same
5.0.6 is good for me

**Comment by loyess** [comment]
@qwerttvv  https://622-7190986-gh.circle-artifacts.com/0/apk/mobile/debug/mobile-universal-debug.apk

**Comment by qwerttvv** [comment]
> @qwerttvv https://622-7190986-gh.circle-artifacts.com/0/apk/mobile/debug/mobile-universal-debug.apk

thx！ i see your post at https://github.com/cbeuw/Cloak-android/issues/13#issuecomment-663998837
