### ISSUE TITLE
Not able to access ftp site on 5.1.x

### ISSUE THREAD

**Issue by xygwfxu** [shadowsocks/shadowsocks-android#2621]
Install 5.1.6 on Android 10, enable a profile. Access site: ftp://ftp.fedex.com/pub/us/software/

Not able to open this site. However it works on version 5.0.6.
Check server access log,  even no log for that site.

**Comment by madeye** [comment]
It looks an issue of shadowsocks-rust. I cannot get FTP client with the a shadowsocks-rust setup locally.

@zonyitoo To get FTP works, we need to establish the TCP relay even there's no request sent from client. Can you double check this?

**Comment by madeye** [comment]
@zonyitoo here is a similar fix for shadowsocks-libev before: https://github.com/shadowsocks/shadowsocks-libev/commit/fa82628dd938ee5285cbce481cc722539d8ade2a

When a new socks5 client connected, with a small duration, we would establish a TCP relay to the remote shadowsocks server even if there's no data sent from the client.

**Comment by zonyitoo** [comment]
> @zonyitoo To get FTP works, we need to establish the TCP relay even there's no request sent from client. Can you double check this?

I understand. But why? Why FTP requires proxy server to connect to remote without data sent?

**Comment by madeye** [comment]
FTP is a very old protocol. Imaging a telnet session in the late 90s,

1. You establish a TCP connection to a server port, 
2. The server first send a prompt to ask for your login info,
3. You follow the prompt to send username and password.
4. The server will tell you if the login is successful or not.

And it's similar for FTP, here is a diagram I found: https://www.eventhelix.com/RealtimeMantra/Networking/FTP.pdf

Generally, if a TCP protocol requires the server to send the prompt first, it cannot work with the current shadowsocks-rust.

**Comment by zonyitoo** [comment]
Got it.

**Comment by Mygod** [comment]
This is fixed? Should we close it?

**Comment by madeye** [comment]
Nope, I think we have to wait until the next release of shadowsocks-rust.

**Comment by zonyitoo** [comment]
I have already fixed in `feature-separate-crates` branch. But I haven't finished migrating dns-relay, yet.

**Comment by xygwfxu** [comment]
Verified on v5.1.8, issue is still there. Not able to access ftp resource.

**Comment by madeye** [comment]
@xygwfxu Try again, it should work now.

**Comment by xygwfxu** [comment]
@madeye  The  version I tried is v5.1.8 which is the current latest. what do you mean to retry for same version?

I thought you released two builds with same version number and just tried again. Same error.

**Comment by madeye** [comment]
I can connect to FTP site with 5.1.8.

Any step to reproduce your issue?

**Comment by xygwfxu** [comment]
ic.
My ftp server is in same host of server from filezilla, then use vlc to connect this ftp server.

**Comment by madeye** [comment]
> My ftp server is in same host of server from filezilla, then use vlc to connect this ftp server.

It looks an issue of VLC. I cannot open the ftp.fedex.com even without shadowsocks.

Please try open ftp://ftp.fedex.com/pub/ in Chrome. It should work now.

**Comment by xygwfxu** [comment]
ok, ok.
My bad, I shouldn't thought these are same issues. At that moment,I just want simplifying how to reproduce such issue. so I gave a public ftp server for you. and yes this public ftp resource works on 5.1.8.

Not sure whats the diff here, however If you could you can setup a your own windowds filezilla ftp server, set to same subnet of you ss server like 192.168.1.x.  then please try to access it like " ftp://192.168.1.< ftp ip>" in chrome to see if it works.

 In my test results, it same as vlc which its failed.

**Comment by madeye** [comment]
@xygwfxu I just setup a FTP server with `vsftpd` and everything works fine in Chrome.

Also, can you make sure 5.0.6 works for your FTP server in VLC? I tried 5.0.6 with a FTP server in VLC and it cannot work either. In fact, VLC cannot work with any of my FTP server...

**Comment by xygwfxu** [comment]
thats so strange. 
I use vlc to watch movies from my ftp server for months on v5.0.6.  And this is the only issue that blocks me to upgrade to v5.1.x :(

**Comment by xygwfxu** [comment]
![Uploading Screenshot_2021-01-01-13-13-44-454_org.videolan.vlc.jpg…]()

**Comment by xygwfxu** [comment]
you see I have several resource here.

**Comment by xygwfxu** [comment]
![Uploading Screenshot_2021-01-01-13-13-44-454_org.videolan.vlc.jpg…]()

**Comment by madeye** [comment]
Try this server: ftp://ftpuser:ftpuser@199.180.114.110/

**Comment by xygwfxu** [comment]
ic there is a test. MP4 file in vlc.

**Comment by xygwfxu** [comment]
ic there is a test. MP4 file in vlc.

**Comment by madeye** [comment]
Try open this file in VLC. I can play the video through shadowsocks.

**Comment by xygwfxu** [comment]
@madeye are u saying vlc can open ftp resource on v5.1.8 on your side?

u previous comment mentioned none of works.

bit confuse here.

**Comment by madeye** [comment]
I solved a permission issue in my FTP server, now it can work.

**Comment by xygwfxu** [comment]
okay. so for me its a diff issue.
it works on v5.0.6 not for v5.1.8.

would be kinda acl related/ similar issue cus I use intranet IP?

**Comment by madeye** [comment]
> would be kinda acl related/ similar issue cus I use intranet IP?

What's the route are you using? To access the intranet IPs, you should not bypass LAN IPs.

**Comment by xygwfxu** [comment]
the 3rd one bypass cn ips.

**Comment by madeye** [comment]
I just tried an intranet FTP site through shadowsocks, which also works in VLC.

**Comment by xygwfxu** [comment]
that'bad. I don't know how I can workaround this.

thanks for your great helps anyway.

**Comment by Mygod** [comment]
Just ran into this for SSH. SSH begins with a handshake message of server version. For MobaXterm, it seems to await server's version before sending its own version, which makes the session timeout. I will update and test later.

**Comment by zonyitoo** [comment]
500ms is too long for SSH?

**Comment by madeye** [comment]
I did some tests with JuiceSSH. Everything looks fine.

**Comment by Mygod** [comment]
Sorry I meant this for the old version. It works fine in the latest version.
